--- Cyberpunk highlight group definitions.
local M = {}

--- Apply all highlight groups.
---@param palette CyberpunkPalette
---@param opts table
function M.apply(palette, opts)
  local hl = vim.api.nvim_set_hl

  -- Core syntax
  hl(0, "Normal", { fg = palette.green, bg = opts.transparent and palette.none or palette.black })
  hl(0, "Comment", { fg = palette.cyan, italic = opts.italic_comments })
  hl(0, "Constant", { fg = palette.blue })
  hl(0, "String", { link = "Constant" })
  hl(0, "Character", { link = "Constant" })
  hl(0, "Number", { link = "Constant" })
  hl(0, "Boolean", { link = "Constant" })
  hl(0, "Float", { link = "Number" })
  hl(0, "Special", { fg = palette.special })
  hl(0, "Tag", { link = "Special" })
  hl(0, "SpecialChar", { link = "Special" })
  hl(0, "Delimiter", { link = "Special" })
  hl(0, "SpecialComment", { link = "Special" })
  hl(0, "Debug", { link = "Special" })
  hl(0, "Identifier", { fg = palette.blue, bold = true })
  hl(0, "Statement", { fg = palette.yellow, bold = true })
  hl(0, "Label", { link = "Statement" })
  hl(0, "Keyword", { fg = palette.yellow, bold = opts.bold_keywords, italic = opts.italic_keywords })
  hl(0, "Exception", { link = "Statement" })
  hl(0, "PreProc", { fg = palette.cyan })
  hl(0, "Include", { link = "PreProc" })
  hl(0, "Define", { link = "PreProc" })
  hl(0, "Macro", { link = "PreProc" })
  hl(0, "PreCondit", { link = "PreProc" })
  hl(0, "Type", { fg = palette.yellow, bold = true })
  hl(0, "StorageClass", { link = "Type" })
  hl(0, "Structure", { link = "Type" })
  hl(0, "Typedef", { link = "Type" })
  hl(0, "Function", { fg = palette.green, bold = opts.bold_functions })
  hl(0, "Repeat", { fg = palette.yellow })
  hl(0, "Conditional", { link = "Repeat" })
  hl(0, "Operator", { fg = palette.red })
  hl(0, "Ignore", { fg = palette.black })
  hl(0, "Error", { fg = palette.red, bg = palette.dark_purple })
  hl(0, "Todo", { fg = palette.blue, bg = palette.yellow })

  -- Popup menu
  hl(0, "Pmenu", { fg = palette.black, bg = palette.green })
  hl(0, "PmenuSel", { fg = palette.blue, bg = palette.yellow })

  -- UI elements
  hl(0, "LineNr", { fg = palette.dark_fg })
  hl(0, "CursorLineNr", { fg = palette.yellow, bold = true })
  hl(0, "CursorLine", { bg = palette.dark_bg })
  hl(0, "CursorColumn", { bg = palette.dark_bg })
  hl(0, "ColorColumn", { bg = palette.dark_bg })
  hl(0, "Visual", { bg = palette.visual })
  hl(0, "VisualNOS", { bg = palette.visual })
  hl(0, "Search", { fg = palette.black, bg = palette.yellow })
  hl(0, "IncSearch", { fg = palette.black, bg = palette.cyan })
  hl(0, "MatchParen", { fg = palette.yellow, bg = palette.visual })
  hl(0, "StatusLine", { fg = palette.green, bg = palette.dark_bg })
  hl(0, "StatusLineNC", { fg = palette.dark_fg, bg = palette.dark_bg })
  hl(0, "VertSplit", { fg = palette.dark_fg })
  hl(0, "WinSeparator", { fg = palette.dark_fg })
  hl(0, "Folded", { fg = palette.cyan, bg = palette.dark_bg })
  hl(0, "FoldColumn", { fg = palette.cyan, bg = palette.dark_bg })
  hl(0, "SignColumn", { bg = palette.none })
  hl(0, "NonText", { fg = palette.dark_fg })
  hl(0, "SpecialKey", { fg = palette.dark_fg })
  hl(0, "Title", { fg = palette.yellow, bold = true })
  hl(0, "Directory", { fg = palette.cyan })
  hl(0, "WildMenu", { fg = palette.black, bg = palette.yellow })
  hl(0, "TabLine", { fg = palette.dark_fg, bg = palette.dark_bg })
  hl(0, "TabLineSel", { fg = palette.green, bg = palette.black })
  hl(0, "TabLineFill", { bg = palette.dark_bg })

  -- Diff
  hl(0, "DiffAdd", { bg = palette.diff_green })
  hl(0, "DiffChange", { bg = palette.diff_blue })
  hl(0, "DiffDelete", { fg = palette.red, bg = palette.diff_red })
  hl(0, "DiffText", { bg = palette.dark_purple, bold = true })

  -- Diagnostics (Neovim LSP)
  hl(0, "DiagnosticError", { fg = palette.red })
  hl(0, "DiagnosticWarn", { fg = palette.yellow })
  hl(0, "DiagnosticInfo", { fg = palette.blue })
  hl(0, "DiagnosticHint", { fg = palette.cyan })
  hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = palette.red })
  hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = palette.yellow })
  hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = palette.blue })
  hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = palette.cyan })

  -- Spell
  hl(0, "SpellBad", { undercurl = true, sp = palette.red })
  hl(0, "SpellCap", { undercurl = true, sp = palette.blue })
  hl(0, "SpellRare", { undercurl = true, sp = palette.special })
  hl(0, "SpellLocal", { undercurl = true, sp = palette.cyan })

  -- Treesitter
  hl(0, "@comment", { link = "Comment" })
  hl(0, "@constant", { link = "Constant" })
  hl(0, "@constant.builtin", { fg = palette.blue, bold = true })
  hl(0, "@constant.macro", { link = "Macro" })
  hl(0, "@string", { link = "String" })
  hl(0, "@string.escape", { fg = palette.special })
  hl(0, "@string.regex", { fg = palette.cyan })
  hl(0, "@string.special", { fg = palette.special })
  hl(0, "@character", { link = "Character" })
  hl(0, "@number", { link = "Number" })
  hl(0, "@boolean", { link = "Boolean" })
  hl(0, "@float", { link = "Float" })
  hl(0, "@function", { fg = palette.green, bold = opts.bold_functions })
  hl(0, "@function.builtin", { fg = palette.green, bold = true })
  hl(0, "@function.call", { fg = palette.green })
  hl(0, "@function.macro", { fg = palette.cyan })
  hl(0, "@method", { fg = palette.green })
  hl(0, "@method.call", { fg = palette.green })
  hl(0, "@constructor", { fg = palette.yellow })
  hl(0, "@parameter", { fg = palette.blue, italic = true })
  hl(0, "@keyword", { fg = palette.yellow, bold = opts.bold_keywords, italic = opts.italic_keywords })
  hl(0, "@keyword.function", { fg = palette.yellow, italic = opts.italic_keywords })
  hl(0, "@keyword.operator", { fg = palette.red })
  hl(0, "@keyword.return", { fg = palette.yellow, bold = true })
  hl(0, "@conditional", { link = "Conditional" })
  hl(0, "@repeat", { link = "Repeat" })
  hl(0, "@label", { link = "Label" })
  hl(0, "@operator", { link = "Operator" })
  hl(0, "@exception", { link = "Exception" })
  hl(0, "@variable", { fg = palette.green })
  hl(0, "@variable.builtin", { fg = palette.blue, italic = true })
  hl(0, "@type", { link = "Type" })
  hl(0, "@type.builtin", { fg = palette.yellow })
  hl(0, "@type.definition", { link = "Typedef" })
  hl(0, "@type.qualifier", { fg = palette.yellow, italic = true })
  hl(0, "@namespace", { fg = palette.cyan })
  hl(0, "@include", { link = "Include" })
  hl(0, "@preproc", { link = "PreProc" })
  hl(0, "@define", { link = "Define" })
  hl(0, "@field", { fg = palette.blue })
  hl(0, "@property", { fg = palette.blue })
  hl(0, "@punctuation.bracket", { fg = palette.special })
  hl(0, "@punctuation.delimiter", { fg = palette.special })
  hl(0, "@punctuation.special", { fg = palette.cyan })
  hl(0, "@tag", { fg = palette.yellow })
  hl(0, "@tag.attribute", { fg = palette.green, italic = true })
  hl(0, "@tag.delimiter", { fg = palette.special })
  hl(0, "@text", { fg = palette.green })
  hl(0, "@text.strong", { bold = true })
  hl(0, "@text.emphasis", { italic = true })
  hl(0, "@text.underline", { underline = true })
  hl(0, "@text.strike", { strikethrough = true })
  hl(0, "@text.title", { fg = palette.yellow, bold = true })
  hl(0, "@text.literal", { fg = palette.cyan })
  hl(0, "@text.uri", { fg = palette.blue, underline = true })
  hl(0, "@text.reference", { fg = palette.blue })

  -- LSP semantic tokens
  hl(0, "@lsp.type.class", { link = "Type" })
  hl(0, "@lsp.type.decorator", { fg = palette.cyan })
  hl(0, "@lsp.type.enum", { link = "Type" })
  hl(0, "@lsp.type.enumMember", { link = "Constant" })
  hl(0, "@lsp.type.function", { link = "@function" })
  hl(0, "@lsp.type.interface", { fg = palette.cyan, bold = true })
  hl(0, "@lsp.type.keyword", { link = "@keyword" })
  hl(0, "@lsp.type.macro", { link = "Macro" })
  hl(0, "@lsp.type.method", { link = "@method" })
  hl(0, "@lsp.type.namespace", { link = "@namespace" })
  hl(0, "@lsp.type.parameter", { link = "@parameter" })
  hl(0, "@lsp.type.property", { link = "@property" })
  hl(0, "@lsp.type.struct", { link = "Structure" })
  hl(0, "@lsp.type.type", { link = "Type" })
  hl(0, "@lsp.type.typeParameter", { fg = palette.yellow, italic = true })
  hl(0, "@lsp.type.variable", { link = "@variable" })
  hl(0, "@lsp.mod.deprecated", { strikethrough = true })

  -- Git signs (gitsigns.nvim)
  hl(0, "GitSignsAdd", { fg = palette.green })
  hl(0, "GitSignsChange", { fg = palette.blue })
  hl(0, "GitSignsDelete", { fg = palette.red })

  -- Apply user overrides
  if opts.overrides then
    for group, settings in pairs(opts.overrides) do
      hl(0, group, settings)
    end
  end
end

return M
